services:
  - type: web
    name: calculator-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000